apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: ggce
data:
  traefik.yml: |
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
    providers:
      kubernetesCRD: {}
      kubernetesIngress:
        publishedService: "ggce/reverse-proxy"
    api:
      dashboard: true
    log:
      level: DEBUG
    accessLog: {}
